name: hpo
dependencies:
  - python=3.8
  - numpy
  - pandas
  - matplotlib
  - pytorch
  - jupyter
  - pip
  - pip:
      - optuna
      - ray
      - ray[tune]
      - scikit-optimize
      - bayesian-optimization
      - tensorboard
      - seaborn
      - progressbar
